[env]
# supports arbitrary env vars so rtx can be used like direnv/dotenv
# NODE_ENV = 'production'

[tools]
node = ["22.14.0", "20.17.0", "18.20.7"]
ruby = ['3.4.1', '3.3.6', '3.2.6']
python = ['3.13.1']
golang = ['1.19.1']
terraform = ['1.9.7']
pnpm = '9'
# flutter = ['3.22.0-stable']
# java = ['adoptopenjdk-17.0.9+9']

# send arbitrary options to the plugin, passed as:
# RTX_TOOL_OPTS__VENV=.venv
# python = {version='3.10', virtualenv='.venv'}

[alias]
# specify a custom repo url
# note this will only be used if the plugin does not already exist
python = 'https://github.com/asdf-community/asdf-python'
ruby = 'https://github.com/asdf-vm/asdf-ruby.git'
node = 'https://github.com/asdf-vm/asdf-nodejs.git'
golang = 'https://github.com/asdf-community/asdf-golang.git'
flutter = 'https://github.com/oae/asdf-flutter.git'
java = 'https://github.com/halcyon/asdf-java.git'


[settings]
legacy_version_file = true # enabled by default (unlike asdf)
trusted_config_paths = []
